language: python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tmux

python:
    - "2.7"
    - "3.4"
    - "pypy"

matrix:
    allow_failures:
        - python: "pypy"

install:
    - "pip install blessings==1.6 termcast-client==0.1.3 tmuxp==0.1.12"

script:
    - nosetests
